spring.application.name=referral-service
server.port=8082

# Database
spring.datasource.url=jdbc:postgresql://localhost:5432/referral_db
spring.datasource.username=postgres
spring.datasource.password=root
spring.datasource.driver-class-name=org.postgresql.Driver

# JPA / Hibernate
spring.jpa.hibernate.ddl-auto=validate
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.properties.hibernate.jdbc.batch_size=50
spring.jpa.properties.hibernate.order_inserts=true
spring.jpa.properties.hibernate.order_updates=true

# Flyway
spring.flyway.enabled=true
spring.flyway.locations=classpath:db/migration

# JWT — must match the same secret as auth-service
app.jwt.secret=dGhpcy1pcy1hLXNlY3JldC1rZXktZm9yLXBycm1zLWFwcGxpY2F0aW9uLTI1Ni1iaXRzLWxvbmc=
app.jwt.expiration=86400000

# Patient Service URL
services.patient.url=http://localhost:8081

spring.cloud.loadbalancer.enabled=false
spring.cloud.openfeign.httpclient.hc5.enabled=true