spring.application.name=auth-service
server.port=8080

# Database
spring.datasource.url=jdbc:postgresql://localhost:5432/auth_db
spring.datasource.username=postgres
spring.datasource.password=root
spring.datasource.driver-class-name=org.postgresql.Driver

# JPA / Hibernate
spring.jpa.hibernate.ddl-auto=validate
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

# Flyway
spring.flyway.enabled=true
spring.flyway.locations=classpath:db/migration

# JWT
app.jwt.secret=dGhpcy1pcy1hLXNlY3JldC1rZXktZm9yLXBycm1zLWFwcGxpY2F0aW9uLTI1Ni1iaXRzLWxvbmc=
app.jwt.expiration=86400000